version: "3"
services:
  db:
    build: .
    ports:
      - "5432:5432"
      - "8300:8300"
      - "8301:8301:8301/udp"
      - "8302:8302:8302/udp"
      - "8500:8500"
      - "8600:8600:8600/udp"
    environment:
      - POSTGRES_PASSWORD=postgres